### ISSUE TITLE
Unable to select City in Location

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/lead-marketplace#15]
I can select only sub locality not the city in Location dropdown. I should be able to select both of them.

**Comment by tjtarunkumar** [comment]
Fixed.

**Comment by rohitmanglik** [comment]
Now Location and Sub Location are merged into one. I am unable to differentiate which one is location and which one is sub location.

**Comment by tjtarunkumar** [comment]
Fixed
