### ISSUE TITLE
Only very few categories are visible

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/lead-marketplace#16]
We have around 2.5k Categories that will increase to 7-8k once the complete data is uploaded. 

I am able to see only 15-20 categoeries in drop down.

Screenshots:
https://s30.postimg.org/gvq914oa5/Capture1.png
https://s30.postimg.org/aw2hxh3hp/Capture.png

**Comment by tjtarunkumar** [comment]
Fixed.

**Comment by rohitmanglik** [comment]
Still the same issue.

**Comment by tjtarunkumar** [comment]
please check.
