### ISSUE TITLE
Create a tab for EMail Templates

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/lead-marketplace#18]
Create a new tab of EMail templates.  Also define the placeholders. E.g. {name_lead} should change to name of the lead.

Right now we need only one template i.e. For promotional leads.

**Comment by tjtarunkumar** [comment]
Done

**Comment by rohitmanglik** [comment]
Template details are missing.

**Comment by tjtarunkumar** [comment]
fixed
