### ISSUE TITLE
Promotional Lead Checkbox

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/lead-marketplace#25]
In Lead Capture form, create a select box with title "Is it a promotional lead?". - It should be unselected by default.

If that check box is selected, we should retain current functionality.

If that check box is not selected, we should just save the user details in table "edugorilla_lead" without sending any details to anyone.

**Comment by tjtarunkumar** [comment]
fixed.

**Comment by rohitmanglik** [comment]
If I don't select anything. It shows an empty popup. This popup should just say entry saved or should not be there.

**Comment by tjtarunkumar** [comment]
fixed
