### ISSUE TITLE
EMail Template

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/lead-marketplace#35]
Please verify whether following email template is supported:

Subject: New Lead from EduGorilla: {category}

Content:
Dear {Contact_Person},

In EduGorilla, India's largest Education Community, one student has inquired about {category} in {location} 

Your Institute is listed in before mentioned category on our site. Your listing URL: {listing_URL}

Student's Details:
Name: {name}
Contact: {contact no}
E-Mail Address: {email address}
Full Query: {query}

Please get in touch with the student. 

Feel free to contact me if you have any queries.

Regards
Priyanka Kapoor
Institute Support Specialist
EduGorilla Team

**Comment by tjtarunkumar** [comment]
Done.
