### ISSUE TITLE
Database Structure

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/lead-marketplace#5]
1) Rename edugorilla_lead table to edugorilla_lead_contact_log
2) Create table wp_edugorilla_lead that will contact details of only lead -> Name, Contact No, Email, Category, Location, Query.
3) Remove unnecessary columns from edugorilla_lead_contact_log and link foreign key with wp_edugorilla_lead

**Comment by tjtarunkumar** [comment]
Done.
