### ISSUE TITLE
View and Edit options are not working

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/lead-marketplace#51]
1) Promotions lead sent-> leads should not have view and edit option.
2) Promotions lead sent -> promotion sent should take us to listing page of view and edit respectively. Edit example: http://stg1.edugorilla.com/wp-admin/post.php?post=894&action=edit, View example: http://stg1.edugorilla.com/educations/music-lectures/

**Comment by rohitmanglik** [comment]
Just checked in staging server. View and edit are still not working.

**Comment by tjtarunkumar** [comment]
now it is working.
