### ISSUE TITLE
Email template for Educash Transfer

### ISSUE THREAD

**Issue by anantharam** [rohitmanglik/lead-marketplace#59]
Currently the Tab2 is empty, we would need to use the following template there which should be sent whenever any user receives any amount of EduCash.

```
Dear {Contact_Person},


You have received {ReceivedCount} EduCash from your recent transaction. Your current EduCash balance is  {EduCashCount}.


You can use EduCash to buy student leads from EduGorilla, India's largest Education Community. You can also use your EduCash to buy items in EduGorilla marketplace. Please refer to {EduCashUrl} for more info about EduCash.


Feel free to contact me if you have any queries regarding EduCash.


Regards,
Priyanka Kapoor
Institute Support Specialist
EduGorilla Team
```

**Comment by Akshat091296** [comment]
What is some educash is deducted from a user's account ?

**Comment by rohitmanglik** [comment]
@Akshat091296 It should be:

`
Dear {Contact_Person},


{ReceivedCount} EduCash has been deducted from your account. Your current EduCash balance is  {EduCashCount}.


You can use EduCash to buy student leads from EduGorilla, India's largest Education Community. You can also use your EduCash to buy items in EduGorilla marketplace. Please refer to {EduCashUrl} for more info about EduCash.


Feel free to contact me if you have any queries regarding EduCash.


Regards,
Priyanka Kapoor
Institute Support Specialist
EduGorilla Team
`

**Comment by Akshat091296** [comment]
Okay sir

**Comment by rohitmanglik** [comment]
I added an entry just now but did not receive any email yet.
