### ISSUE TITLE
OTP

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/lead-marketplace#6]
Create an admin panel to send OTP to the user.

**Comment by rohitmanglik** [comment]
Pick Gupshup details from Wordpress Constants or an admin panel. We can commit login details on GitHub

**Comment by rohitmanglik** [comment]
Please update status over here.

**Comment by rohitmanglik** [comment]
@tjtarunkumar I just checked the OTP screen. It doesn't display the 4 digit number sent to user for verification.

It should display the OTP sent to the user.

**Comment by tjtarunkumar** [comment]
fixed
