### ISSUE TITLE
Filter is not working in this use case

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/lead-marketplace#80]
![image](https://cloud.githubusercontent.com/assets/677634/21840348/0f50d1ec-d803-11e6-9773-aa2be75f3050.png)

Also there is no popup

**Comment by rohitmanglik** [comment]
Still not working. Plus it's showing two popups.


![image](https://cloud.githubusercontent.com/assets/677634/21857412/5ba1133e-d84b-11e6-815c-2893a7e56924.png)

![image](https://cloud.githubusercontent.com/assets/677634/21857426/644b85e6-d84b-11e6-9c83-b7afb4ea0967.png)

**Comment by tjtarunkumar** [comment]
Please clear your browser cache.
