### ISSUE TITLE
Create Admin Panel to allocate EduCash

### ISSUE THREAD

**Issue by rohitmanglik** [rohitmanglik/lead-marketplace#9]
Create an Admin panel to allocate EduCash.

All the transactions through this portal should be saved in Logs. 

Users with Admin privileges should be able to view the logs.

**Comment by rohitmanglik** [comment]
@Akshat091296 Please mention all the points over here and try to make commits as soon as there is any update. Please don't wait for the code to finish. 

Thanks

**Comment by Akshat091296** [comment]
Ok sir, actually there were some bugs, that's why I didn't commit.
Tomorrow I will commit it.

**Comment by Akshat091296** [comment]
Sir, I have created additional two menus in the admin menu section. One of them is to allot educash, and the other is to view the history of educash transactions. History can be filtered by admin name, client name and also date. Please let me know if I have missed something.
